###########
# BUILDER #
###########
FROM node:lts-slim as builder

COPY package.json package-lock.json ./
RUN npm install && mkdir /frontend && mv ./node_modules ./frontend

WORKDIR /frontend
COPY . .

RUN npm run build

#########
# FINAL #
#########
FROM nginx:1.19.2-alpine
COPY --from=builder /frontend/dist /usr/share/nginx/html
COPY --from=builder /frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80 443
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
