#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo 'Begin local Django start script'

python manage.py migrate

python manage.py update_site_name

exec python manage.py runserver 0.0.0.0:8000
