# Generated by Django 5.1.6 on 2025-03-03 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=200, null=True)),
                ("reference", models.CharField(max_length=200, null=True)),
                (
                    "provider",
                    models.CharField(choices=[("TELEGRAM", "Telegram")], max_length=20),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SETUP", "Setup"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="SETUP",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatLinkingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_uuid", models.UUIDField(null=True, unique=True)),
                ("temp_uuid_created", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linking_sessions",
                        to="core.chat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("SENDING_FAILED", "Sending Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chat",
                    ),
                ),
                (
                    "notified_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.notifiedproduct",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state", "ACTIVE"),
                        ("number__isnull", False),
                        ("reference__isnull", False),
                    ),
                    models.Q(
                        ("state", "INACTIVE"),
                        ("number__isnull", False),
                        ("reference__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="check_non_null_number_reference_when_active_or_inactive",
            ),
        ),
    ]
