# Generated by Django 5.1.6 on 2025-03-03 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_chat_chatlinkingsession_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlinkingsession",
            name="temp_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
