# Generated by Django 5.1.6 on 2025-02-22 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_userselectedkeywords_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notifiedproduct",
            old_name="name",
            new_name="product_name",
        ),
        migrations.RemoveField(
            model_name="notifiedproduct",
            name="user",
        ),
        migrations.AddField(
            model_name="notifiedproduct",
            name="img",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="notifiedproduct",
            name="keywords",
            field=models.ManyToManyField(
                related_name="notified_products", to="core.userselectedkeywords"
            ),
        ),
        migrations.AlterField(
            model_name="notifiedproduct",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="notifiedproduct",
            name="sublocation",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userselectedkeywords",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_keywords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
