# Generated by Django 5.1.6 on 2025-03-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_chatlinkingsession_temp_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatlinkingsession",
            old_name="temp_uuid",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="chatlinkingsession",
            old_name="temp_uuid_created",
            new_name="uuid_created",
        ),
        migrations.AlterField(
            model_name="message",
            name="notified_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="core.notifiedproduct",
            ),
        ),
    ]
