# Generated by Django 5.1.6 on 2025-02-22 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_name_notifiedproduct_product_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notifiedproduct",
            name="keywords",
            field=models.ManyToManyField(
                related_name="notified_products", to="core.keywords"
            ),
        ),
        migrations.DeleteModel(
            name="UserSelectedKeywords",
        ),
        migrations.AddConstraint(
            model_name="keywords",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_name_combo"
            ),
        ),
    ]
