# Generated by Django 5.1.6 on 2025-02-22 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_keywords_alter_notifiedproduct_keywords_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Keywords",
            new_name="Keyword",
        ),
    ]
