# Generated by Django 5.1.6 on 2025-03-04 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_temp_uuid_chatlinkingsession_uuid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="check_non_null_number_reference_when_active_or_inactive",
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state", "ACTIVE"),
                        ("number__isnull", False),
                        ("reference__isnull", False),
                    ),
                    models.Q(
                        ("state", "INACTIVE"),
                        ("number__isnull", False),
                        ("reference__isnull", False),
                    ),
                    ("state", "SETUP"),
                    _connector="OR",
                ),
                name="check_non_null_number_reference_when_active_or_inactive",
            ),
        ),
    ]
