# Generated by Django 5.1.6 on 2025-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0006_remove_chat_check_non_null_number_reference_when_active_or_inactive_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sent_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("BOT", "Bot"), ("USER", "User")], default="BOT", max_length=30
            ),
            preserve_default=False,
        ),
    ]
