# Generated by Django 5.1.6 on 2025-03-07 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_chatlinkingsession_uuid_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.UniqueConstraint(
                fields=("reference", "provider"), name="unique_reference_provider_combo"
            ),
        ),
    ]
