# Generated by Django 5.1.6 on 2025-03-08 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_chat_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="check_non_null_number_reference_when_active_or_inactive",
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "ACTIVE"), ("reference__isnull", False)),
                    models.Q(("state", "INACTIVE"), ("reference__isnull", False)),
                    ("state", "SETUP"),
                    _connector="OR",
                ),
                name="check_non_null_reference_when_active_or_inactive",
            ),
        ),
    ]
