# Generated by Django 5.1.6 on 2025-03-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_chat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="error_msg",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=30,
            ),
        ),
    ]
