# Generated by Django 5.1.6 on 2025-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_message_error_msg_message_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifiedproduct",
            name="status",
        ),
        migrations.AddField(
            model_name="notifiedproduct",
            name="messages_scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
