# Generated by Django 5.1.6 on 2025-03-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_message_retry_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="error_res_code",
            field=models.CharField(null=True),
        ),
    ]
