# Generated by Django 5.1.6 on 2025-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_message_error_res_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="error_res_code",
            field=models.IntegerField(null=True),
        ),
    ]
