# Generated by Django 5.1.6 on 2025-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_message_error_res_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifiedproduct",
            name="messages_scheduled",
        ),
        migrations.AddField(
            model_name="notifiedproduct",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("KEYWORDS_LINKED", "Keywords Linked"),
                    ("MESSAGES_CREATED", "Messages Created"),
                    ("IRRELEVANT", "Irrelevant"),
                ],
                default="CREATED",
                max_length=30,
            ),
        ),
    ]
