# Generated by Django 5.1.6 on 2025-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_notifiedproduct_messages_scheduled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("domain", models.CharField(max_length=200)),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(null=True)),
                ("fail_count", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "port"), name="unique_domain_port_combo"
                    )
                ],
            },
        ),
    ]
