#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo 'Begin prod Django start script'

# python /app/manage.py collectstatic --noinput

# python /app/manage.py update_site_name

# exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
